/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package feifood.view;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author zeros
 */
public class AlimentoItemPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form AlimentoItemPanel
     */
    public AlimentoItemPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NomeLabel = new javax.swing.JLabel();
        ValorLabel = new javax.swing.JLabel();
        DetalhesButton = new javax.swing.JButton();
        PlusButton = new javax.swing.JButton();
        MinusButton = new javax.swing.JButton();
        QuantidadeTextoLabel = new javax.swing.JLabel();
        QuantidadeValorLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        NomeLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NomeLabel.setText("PLACEHOLDER<NOME>");

        ValorLabel.setText("PLACEHOLDER<VALOR>");

        DetalhesButton.setText("Detalhes");

        PlusButton.setText("+");
        PlusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlusButtonActionPerformed(evt);
            }
        });

        MinusButton.setText("-");
        MinusButton.setEnabled(false);

        QuantidadeTextoLabel.setText("Quantidade no Pedido:");

        QuantidadeValorLabel.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ValorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                        .addComponent(MinusButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PlusButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(QuantidadeTextoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(QuantidadeValorLabel)
                        .addGap(18, 18, 18)
                        .addComponent(DetalhesButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ValorLabel)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 3, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(PlusButton)
                                .addComponent(MinusButton)
                                .addComponent(QuantidadeTextoLabel)
                                .addComponent(QuantidadeValorLabel))
                            .addComponent(DetalhesButton))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PlusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlusButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlusButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DetalhesButton;
    private javax.swing.JButton MinusButton;
    private javax.swing.JLabel NomeLabel;
    private javax.swing.JButton PlusButton;
    private javax.swing.JLabel QuantidadeTextoLabel;
    private javax.swing.JLabel QuantidadeValorLabel;
    private javax.swing.JLabel ValorLabel;
    // End of variables declaration//GEN-END:variables

    public JButton getDetalhesButton() {
        return DetalhesButton;
    }

    public void setDetalhesButton(JButton DetalhesButton) {
        this.DetalhesButton = DetalhesButton;
    }

    public JButton getMinusButton() {
        return MinusButton;
    }

    public void setMinusButton(JButton MinusButton) {
        this.MinusButton = MinusButton;
    }

    public JLabel getNomeLabel() {
        return NomeLabel;
    }

    public void setNomeLabel(JLabel NomeLabel) {
        this.NomeLabel = NomeLabel;
    }

    public JButton getPlusButton() {
        return PlusButton;
    }

    public void setPlusButton(JButton PlusButton) {
        this.PlusButton = PlusButton;
    }

    public JLabel getQuantidadeTextoLabel() {
        return QuantidadeTextoLabel;
    }

    public void setQuantidadeTextoLabel(JLabel QuantidadeTextoLabel) {
        this.QuantidadeTextoLabel = QuantidadeTextoLabel;
    }

    public JLabel getQuantidadeValorLabel() {
        return QuantidadeValorLabel;
    }

    public void setQuantidadeValorLabel(JLabel QuantidadeValorLabel) {
        this.QuantidadeValorLabel = QuantidadeValorLabel;
    }

    public JLabel getValorLabel() {
        return ValorLabel;
    }

    public void setValorLabel(JLabel ValorLabel) {
        this.ValorLabel = ValorLabel;
    }
    
    
}
