package feifood.view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextPane;

public class AlimentoInfoFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AlimentoInfoFrame.class.getName());

    /**
     * Creates new form AlimentoInfoFrame
     */
    public AlimentoInfoFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundPanel = new javax.swing.JPanel();
        VoltarButton = new javax.swing.JButton();
        NomeLabel = new javax.swing.JLabel();
        NomeScroll = new javax.swing.JScrollPane();
        NomeText = new javax.swing.JTextPane();
        ValorLabel = new javax.swing.JLabel();
        ValorScroll = new javax.swing.JScrollPane();
        ValorText = new javax.swing.JTextPane();
        TipoLabel = new javax.swing.JLabel();
        TipoScroll = new javax.swing.JScrollPane();
        TipoText = new javax.swing.JTextPane();
        InformacoesAlimentoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BackgroundPanel.setBackground(new java.awt.Color(211, 237, 255));

        VoltarButton.setText("Voltar");

        NomeLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        NomeLabel.setText("Nome:");

        NomeScroll.setBorder(null);
        NomeScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        NomeText.setEditable(false);
        NomeText.setBackground(new java.awt.Color(211, 237, 255));
        NomeText.setBorder(null);
        NomeText.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        NomeText.setForeground(new java.awt.Color(102, 102, 102));
        NomeScroll.setViewportView(NomeText);

        ValorLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        ValorLabel.setText("Valor:");

        ValorScroll.setBorder(null);
        ValorScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        ValorText.setEditable(false);
        ValorText.setBackground(new java.awt.Color(211, 237, 255));
        ValorText.setBorder(null);
        ValorText.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        ValorText.setForeground(new java.awt.Color(102, 102, 102));
        ValorText.setAutoscrolls(false);
        ValorScroll.setViewportView(ValorText);

        TipoLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        TipoLabel.setText("Tipo:");

        TipoScroll.setBorder(null);
        TipoScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        TipoText.setEditable(false);
        TipoText.setBackground(new java.awt.Color(211, 237, 255));
        TipoText.setBorder(null);
        TipoText.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        TipoText.setForeground(new java.awt.Color(102, 102, 102));
        TipoScroll.setViewportView(TipoText);

        InformacoesAlimentoLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        InformacoesAlimentoLabel.setText("Informações do Alimento");

        javax.swing.GroupLayout BackgroundPanelLayout = new javax.swing.GroupLayout(BackgroundPanel);
        BackgroundPanel.setLayout(BackgroundPanelLayout);
        BackgroundPanelLayout.setHorizontalGroup(
            BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InformacoesAlimentoLabel)
                    .addGroup(BackgroundPanelLayout.createSequentialGroup()
                        .addComponent(NomeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NomeScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(VoltarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BackgroundPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ValorLabel)
                            .addComponent(TipoLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TipoScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                            .addComponent(ValorScroll))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        BackgroundPanelLayout.setVerticalGroup(
            BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InformacoesAlimentoLabel)
                .addGap(18, 18, 18)
                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NomeLabel)
                    .addComponent(NomeScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ValorLabel)
                    .addComponent(ValorScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TipoLabel)
                    .addComponent(TipoScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(VoltarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AlimentoInfoFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JLabel InformacoesAlimentoLabel;
    private javax.swing.JLabel NomeLabel;
    private javax.swing.JScrollPane NomeScroll;
    private javax.swing.JTextPane NomeText;
    private javax.swing.JLabel TipoLabel;
    private javax.swing.JScrollPane TipoScroll;
    private javax.swing.JTextPane TipoText;
    private javax.swing.JLabel ValorLabel;
    private javax.swing.JScrollPane ValorScroll;
    private javax.swing.JTextPane ValorText;
    private javax.swing.JButton VoltarButton;
    // End of variables declaration//GEN-END:variables

    public JPanel getBackgroundPanel() {
        return BackgroundPanel;
    }

    public void setBackgroundPanel(JPanel BackgroundPanel) {
        this.BackgroundPanel = BackgroundPanel;
    }

    public JLabel getInformacoesAlimentoLabel() {
        return InformacoesAlimentoLabel;
    }

    public void setInformacoesAlimentoLabel(JLabel InformacoesAlimentoLabel) {
        this.InformacoesAlimentoLabel = InformacoesAlimentoLabel;
    }

    public JLabel getNomeLabel() {
        return NomeLabel;
    }

    public void setNomeLabel(JLabel NomeLabel) {
        this.NomeLabel = NomeLabel;
    }

    public JScrollPane getNomeScroll() {
        return NomeScroll;
    }

    public void setNomeScroll(JScrollPane NomeScroll) {
        this.NomeScroll = NomeScroll;
    }

    public JTextPane getNomeText() {
        return NomeText;
    }

    public void setNomeText(JTextPane NomeText) {
        this.NomeText = NomeText;
    }

    public JLabel getTipoLabel() {
        return TipoLabel;
    }

    public void setTipoLabel(JLabel TipoLabel) {
        this.TipoLabel = TipoLabel;
    }

    public JScrollPane getTipoScroll() {
        return TipoScroll;
    }

    public void setTipoScroll(JScrollPane TipoScroll) {
        this.TipoScroll = TipoScroll;
    }

    public JTextPane getTipoText() {
        return TipoText;
    }

    public void setTipoText(JTextPane TipoText) {
        this.TipoText = TipoText;
    }

    public JLabel getValorLabel() {
        return ValorLabel;
    }

    public void setValorLabel(JLabel ValorLabel) {
        this.ValorLabel = ValorLabel;
    }

    public JScrollPane getValorScroll() {
        return ValorScroll;
    }

    public void setValorScroll(JScrollPane ValorScroll) {
        this.ValorScroll = ValorScroll;
    }

    public JTextPane getValorText() {
        return ValorText;
    }

    public void setValorText(JTextPane ValorText) {
        this.ValorText = ValorText;
    }

    public JButton getVoltarButton() {
        return VoltarButton;
    }

    public void setVoltarButton(JButton VoltarButton) {
        this.VoltarButton = VoltarButton;
    }

    
}
