package feifood.view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSeparator;
import javax.swing.JTextField;

public class LoginFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginFrame.class.getName());

    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ErroOptionPane = new javax.swing.JOptionPane();
        BackgroundPanel = new javax.swing.JPanel();
        FEIFoodIcon = new javax.swing.JLabel();
        Separator = new javax.swing.JSeparator();
        TelaDeLoginLabel = new javax.swing.JLabel();
        NomeLabel = new javax.swing.JLabel();
        NomeTextField = new javax.swing.JTextField();
        SenhaLabel = new javax.swing.JLabel();
        SenhaTextField = new javax.swing.JTextField();
        EntrarButton = new javax.swing.JButton();
        CriarContaButton = new javax.swing.JButton();

        ErroOptionPane.setMessage("Erro: nome ou senha estão incorretos.");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FEIFood - Login");

        BackgroundPanel.setBackground(new java.awt.Color(211, 237, 255));

        FEIFoodIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/feifood/view/FEI logo.png"))); // NOI18N

        TelaDeLoginLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        TelaDeLoginLabel.setText("Tela de Login");

        NomeLabel.setText("Nome:");

        NomeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeTextFieldActionPerformed(evt);
            }
        });

        SenhaLabel.setText("Senha:");

        SenhaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenhaTextFieldActionPerformed(evt);
            }
        });

        EntrarButton.setText("Entrar");
        EntrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarButtonActionPerformed(evt);
            }
        });

        CriarContaButton.setText("Criar Conta");
        CriarContaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarContaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackgroundPanelLayout = new javax.swing.GroupLayout(BackgroundPanel);
        BackgroundPanel.setLayout(BackgroundPanelLayout);
        BackgroundPanelLayout.setHorizontalGroup(
            BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundPanelLayout.createSequentialGroup()
                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(FEIFoodIcon))
                    .addGroup(BackgroundPanelLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(TelaDeLoginLabel))
                    .addGroup(BackgroundPanelLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(BackgroundPanelLayout.createSequentialGroup()
                                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SenhaLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(BackgroundPanelLayout.createSequentialGroup()
                                        .addComponent(CriarContaButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(EntrarButton))
                                    .addComponent(SenhaTextField)
                                    .addComponent(NomeTextField))))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        BackgroundPanelLayout.setVerticalGroup(
            BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundPanelLayout.createSequentialGroup()
                .addComponent(FEIFoodIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TelaDeLoginLabel)
                .addGap(31, 31, 31)
                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeLabel)
                    .addComponent(NomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SenhaLabel)
                    .addComponent(SenhaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CriarContaButton)
                    .addComponent(EntrarButton))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NomeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeTextFieldActionPerformed

    private void SenhaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenhaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SenhaTextFieldActionPerformed

    private void EntrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntrarButtonActionPerformed

    private void CriarContaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarContaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CriarContaButtonActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginFrame().setVisible(true));
    }

    public JPanel getBackgroundPanel() {
        return BackgroundPanel;
    }

    public void setBackgroundPanel(JPanel BackgroundPanel) {
        this.BackgroundPanel = BackgroundPanel;
    }

    public JButton getCriarContaButton() {
        return CriarContaButton;
    }

    public void setCriarContaButton(JButton CriarContaButton) {
        this.CriarContaButton = CriarContaButton;
    }

    public JButton getEntrarButton() {
        return EntrarButton;
    }

    public void setEntrarButton(JButton EntrarButton) {
        this.EntrarButton = EntrarButton;
    }

    public JOptionPane getErroOptionPane() {
        return ErroOptionPane;
    }

    public void setErroOptionPane(JOptionPane ErroOptionPane) {
        this.ErroOptionPane = ErroOptionPane;
    }

    public JLabel getFEIFoodIcon() {
        return FEIFoodIcon;
    }

    public void setFEIFoodIcon(JLabel FEIFoodIcon) {
        this.FEIFoodIcon = FEIFoodIcon;
    }

    public JLabel getNomeLabel() {
        return NomeLabel;
    }

    public void setNomeLabel(JLabel NomeLabel) {
        this.NomeLabel = NomeLabel;
    }

    public JTextField getNomeTextField() {
        return NomeTextField;
    }

    public void setNomeTextField(JTextField NomeTextField) {
        this.NomeTextField = NomeTextField;
    }

    public JLabel getSenhaLabel() {
        return SenhaLabel;
    }

    public void setSenhaLabel(JLabel SenhaLabel) {
        this.SenhaLabel = SenhaLabel;
    }

    public JTextField getSenhaTextField() {
        return SenhaTextField;
    }

    public void setSenhaTextField(JTextField SenhaTextField) {
        this.SenhaTextField = SenhaTextField;
    }

    public JSeparator getSeparator() {
        return Separator;
    }

    public void setSeparator(JSeparator Separator) {
        this.Separator = Separator;
    }

    public JLabel getTelaDeLoginLabel() {
        return TelaDeLoginLabel;
    }

    public void setTelaDeLoginLabel(JLabel TelaDeLoginLabel) {
        this.TelaDeLoginLabel = TelaDeLoginLabel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JButton CriarContaButton;
    private javax.swing.JButton EntrarButton;
    private javax.swing.JOptionPane ErroOptionPane;
    private javax.swing.JLabel FEIFoodIcon;
    private javax.swing.JLabel NomeLabel;
    private javax.swing.JTextField NomeTextField;
    private javax.swing.JLabel SenhaLabel;
    private javax.swing.JTextField SenhaTextField;
    private javax.swing.JSeparator Separator;
    private javax.swing.JLabel TelaDeLoginLabel;
    // End of variables declaration//GEN-END:variables
}
