package feifood.view;

import feifood.model.Alimento;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;

public class MenuPrincipalFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipalFrame.class.getName());

    /**
     * Creates new form MenuPrincipalFrame
     */
    public MenuPrincipalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AlimentosScrollPane = new javax.swing.JScrollPane();
        AlimentosPanel = new javax.swing.JPanel();
        BuscarTextField = new javax.swing.JTextField();
        BuscarButton = new javax.swing.JButton();
        ConfirmarPedidoButton = new javax.swing.JButton();
        LimparPedidoButton = new javax.swing.JButton();
        CancelarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AlimentosScrollPane.setBackground(new java.awt.Color(211, 237, 255));
        AlimentosScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        AlimentosPanel.setLayout(new javax.swing.BoxLayout(AlimentosPanel, javax.swing.BoxLayout.Y_AXIS));
        AlimentosScrollPane.setViewportView(AlimentosPanel);

        BuscarButton.setText("Buscar");

        ConfirmarPedidoButton.setBackground(new java.awt.Color(21, 151, 237));
        ConfirmarPedidoButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ConfirmarPedidoButton.setForeground(new java.awt.Color(255, 255, 255));
        ConfirmarPedidoButton.setText("Confirmar Pedido");
        ConfirmarPedidoButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(12, 105, 166), 1, true));
        ConfirmarPedidoButton.setBorderPainted(false);

        LimparPedidoButton.setBackground(new java.awt.Color(21, 151, 237));
        LimparPedidoButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LimparPedidoButton.setForeground(new java.awt.Color(255, 255, 255));
        LimparPedidoButton.setText("Limpar Pedido");
        LimparPedidoButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(13, 109, 173), 1, true));
        LimparPedidoButton.setBorderPainted(false);

        CancelarButton.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AlimentosScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BuscarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BuscarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CancelarButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LimparPedidoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(ConfirmarPedidoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuscarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarButton)
                    .addComponent(CancelarButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AlimentosScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ConfirmarPedidoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LimparPedidoButton, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AlimentosPanel;
    private javax.swing.JScrollPane AlimentosScrollPane;
    private javax.swing.JButton BuscarButton;
    private javax.swing.JTextField BuscarTextField;
    private javax.swing.JButton CancelarButton;
    private javax.swing.JButton ConfirmarPedidoButton;
    private javax.swing.JButton LimparPedidoButton;
    // End of variables declaration//GEN-END:variables

    public JPanel getAlimentosPanel() {
        return AlimentosPanel;
    }

    public void setAlimentosPanel(JPanel AlimentosPanel) {
        this.AlimentosPanel = AlimentosPanel;
    }

    public JScrollPane getAlimentosScrollPane() {
        return AlimentosScrollPane;
    }

    public void setAlimentosScrollPane(JScrollPane AlimentosScrollPane) {
        this.AlimentosScrollPane = AlimentosScrollPane;
    }

    public JButton getBuscarButton() {
        return BuscarButton;
    }

    public void setBuscarButton(JButton BuscarButton) {
        this.BuscarButton = BuscarButton;
    }

    public JTextField getBuscarTextField() {
        return BuscarTextField;
    }

    public void setBuscarTextField(JTextField BuscarTextField) {
        this.BuscarTextField = BuscarTextField;
    }

    public JButton getConfirmarPedidoButton() {
        return ConfirmarPedidoButton;
    }

    public void setConfirmarPedidoButton(JButton ConfirmarPedidoButton) {
        this.ConfirmarPedidoButton = ConfirmarPedidoButton;
    }

    public JButton getLimparPedidoButton() {
        return LimparPedidoButton;
    }

    public void setLimparPedidoButton(JButton LimparPedidoButton) {
        this.LimparPedidoButton = LimparPedidoButton;
    }

    public JButton getCancelarButton() {
        return CancelarButton;
    }

    public void setCancelarButton(JButton CancelarButton) {
        this.CancelarButton = CancelarButton;
    }
}
