package feifood.view;

import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTextField;

public class MenuPrincipalFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipalFrame.class.getName());

    /**
     * Creates new form MenuPrincipalFrame
     */
    public MenuPrincipalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CriarPedidoButton = new javax.swing.JButton();
        AlimentosScrollPane = new javax.swing.JScrollPane();
        AlimentosPanel = new javax.swing.JPanel();
        BuscarTextField = new javax.swing.JTextField();
        BuscarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CriarPedidoButton.setBackground(new java.awt.Color(21, 151, 237));
        CriarPedidoButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CriarPedidoButton.setForeground(new java.awt.Color(255, 255, 255));
        CriarPedidoButton.setText("+ Clique para Criar um Pedido");
        CriarPedidoButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 123, 206), 3));
        CriarPedidoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarPedidoButtonActionPerformed(evt);
            }
        });

        AlimentosScrollPane.setBackground(new java.awt.Color(211, 237, 255));

        AlimentosPanel.setLayout(new java.awt.GridLayout(0, 1, 0, 1));
        AlimentosScrollPane.setViewportView(AlimentosPanel);

        BuscarButton.setText("Buscar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AlimentosScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CriarPedidoButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BuscarTextField)
                        .addGap(18, 18, 18)
                        .addComponent(BuscarButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuscarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AlimentosScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CriarPedidoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CriarPedidoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarPedidoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CriarPedidoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuPrincipalFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AlimentosPanel;
    private javax.swing.JScrollPane AlimentosScrollPane;
    private javax.swing.JButton BuscarButton;
    private javax.swing.JTextField BuscarTextField;
    private javax.swing.JButton CriarPedidoButton;
    // End of variables declaration//GEN-END:variables

    public JScrollPane getAlimentosScrollPane() {
        return AlimentosScrollPane;
    }

    public void setAlimentosScrollPane(JScrollPane AlimentosScrollPane) {
        this.AlimentosScrollPane = AlimentosScrollPane;
    }

    public JButton getBuscarButton() {
        return BuscarButton;
    }

    public void setBuscarButton(JButton BuscarButton) {
        this.BuscarButton = BuscarButton;
    }

    public JTextField getBuscarTextField() {
        return BuscarTextField;
    }

    public void setBuscarTextField(JTextField BuscarTextField) {
        this.BuscarTextField = BuscarTextField;
    }

    public JButton getCriarPedidoButton() {
        return CriarPedidoButton;
    }

    public void setCriarPedidoButton(JButton CriarPedidoButton) {
        this.CriarPedidoButton = CriarPedidoButton;
    }
}
